In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from dotenv import load_dotenv; load_dotenv('C:\git-repository\Blog\.gitignore\.env')
#from dotenv import load_dotenv; load_dotenv("C:\git-repository\BLS_prediction_project\.gitignore\.env")
import requests
import fredapi as fa
import seaborn as sns
import statsmodels.api as sm
from pandas_datareader import data as pdr

<>:5: SyntaxWarning: invalid escape sequence '\g'
<>:5: SyntaxWarning: invalid escape sequence '\g'
C:\Users\paulp\AppData\Local\Temp\ipykernel_42340\1359181946.py:5: SyntaxWarning: invalid escape sequence '\g'
  from dotenv import load_dotenv; load_dotenv('C:\git-repository\Blog\.gitignore\.env')

#### FRED DATA WRANGLING & CLEANING

In [165]:
series = [
    'PAYEMS',
    'UNRATE',
    'ICSA',
    'CCSA',
    'DGS2',
    'DGS10',
    'T10Y2Y',
    'UMCSENT'
    ]

start = '2000-01-01'
end = '2025-01-01'

df = pdr.DataReader(
    series,
    'fred',
    start,
    end
)

In [166]:
fred_df = df.resample('M').mean()
fred_df = fred_df.ffill()

C:\Users\paulp\AppData\Local\Temp\ipykernel_42340\1869457212.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  fred_df = df.resample('M').mean()

In [167]:
fred_df = fred_df.rename(
    columns={
        'PAYEMS': 'payrolls', 
        'UNRATE': 'unemployment_rate', 
        'ICSA': 'initial_claims', 
        'CCSA': 'cont_claims', 
        'DGS2': '2yr_yield', 
        'DGS10': '10yr_yield',
        'T10Y2Y': '10yr_2yr_spread',
        'UMCSENT': 'sentiment'
        }).reset_index()

In [169]:
fred_df['payrolls_lag1'] = fred_df['payrolls'].shift(1)
fred_df['unemployment_rate_3mo_avg'] = fred_df['unemployment_rate'].rolling(3).mean()
fred_df['initial_claims_lag1'] = fred_df['initial_claims'].shift(1)
fred_df['initial_claims_momentum'] = fred_df['initial_claims'].diff(3)
fred_df['cont_claims_lag1'] = fred_df['cont_claims'].shift(1)
fred_df['cont_claims_momentum'] = fred_df['cont_claims'].diff(3)
fred_df['2yr_yield_volatility'] = fred_df['2yr_yield'].rolling(3).std()
fred_df['10yr_yield_volatility'] = fred_df['10yr_yield'].rolling(3).std()

fred_df.head()

,DATE,payrolls,unemployment_rate,initial_claims,cont_claims,2yr_yield,10yr_yield,10yr_2yr_spread,sentiment,payrolls_lag1,unemployment_rate_3mo_avg,initial_claims_lag1,initial_claims_momentum,cont_claims_lag1,cont_claims_momentum,2yr_yield_volatility,10yr_yield_volatility
0,2000-01-31,131011.0,4.0,288400.0,2109800.0,6.440000,6.661000,0.221000,112.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000-02-29,131120.0,4.1,293750.0,2147500.0,6.610500,6.519500,-0.091000,111.3,131011.0,NaN,288400.0,NaN,2109800.0,NaN,NaN,NaN
2,2000-03-31,131604.0,4.0,274750.0,2079000.0,6.528261,6.256522,-0.271739,107.1,131120.0,4.033333,293750.0,NaN,2147500.0,NaN,0.085268,0.205257
3,2000-04-30,131884.0,3.8,271600.0,2015400.0,6.403684,5.990526,-0.413158,109.2,131604.0,3.966667,274750.0,-16800.0,2079000.0,-94400.0,0.104128,0.264488
4,2000-05-31,132105.0,4.0,282250.0,1989500.0,6.809545,6.440455,-0.369091,110.7,131884.0,3.933333,271600.0,-11500.0,2015400.0,-158000.0,0.207912,0.226208

In [ ]:
# NON-FARM PAYROLLS -- MONTHLY

fred_key = os.getenv('fred')
base_url = 'https://api.stlouisfed.org/fred/'
obs_endpoint = 'series/observations'

# series_id = 'PAYEMS'
# start_date = '2000-01-01'
# end_date = '2026-05-01'
# ts_frequency = 'm'
# ts_units = 'lin'

# payems_params = {
#     'series_id': series_id,
#     'api_key': fred_key,
#     'file_type': 'json',
#     'observation_start': start_date,
#     'observation_end': end_date,
#     'frequency': ts_frequency,
#     'units': ts_units
# }

# response = requests.get(base_url + obs_endpoint, params=payems_params)
# data = response.json()
# payems_df = pd.DataFrame(data['observations'])
# payems_df['date'] = pd.to_datetime(payems_df['date'])
# payems_df['value'] = pd.to_numeric(payems_df['value'], errors='coerce')
# payems_df = (
#     payems_df
#     .set_index('date')[['value']]
#     .resample('ME')
#     .last()     # USE LAST OBSERVATION WITH PAYROLLS, AVERAGES DILUTE THE SIGNAL
#     .rename(columns={'value': 'payems'})
# )

In [ ]:
# UNEMPLOYMENT CLAIMS -- WEEKLY

# series_id = 'ICSA'
# start_date = '2000-01-01'
# end_date = '2026-05-01'
# ts_frequency = 'w'
# ts_units = 'lin'

# unemp_claims_params = {
#     'series_id': series_id,
#     'api_key': fred_key,
#     'file_type': 'json',
#     'observation_start': start_date,
#     'observation_end': end_date,
#     'frequency': ts_frequency,
#     'units': ts_units
# }

# response = requests.get(base_url + obs_endpoint, params=unemp_claims_params)
# data = response.json()
# unemp_claims_df = pd.DataFrame(data['observations'])

# unemp_claims_df['date'] = pd.to_datetime(unemp_claims_df['date'])
# unemp_claims_df['value'] = pd.to_numeric(unemp_claims_df['value'], errors='coerce')

# unemp_claims_df = (
#     unemp_claims_df
#     .set_index('date')[['value']]
#     .resample('ME')
#     .mean()
#     .rename(columns={'value': 'unemp_claims'})
# )

In [ ]:
# CONTINUING CLAIMS -- WEEKLY

# series_id = 'CCSA'
# start_date = '2000-01-01'
# end_date = '2026-05-01'
# ts_frequency = 'w'
# ts_units = 'lin'

# cont_claims_params = {
#     'series_id': series_id,
#     'api_key': fred_key,
#     'file_type': 'json',
#     'observation_start': start_date,
#     'observation_end': end_date,
#     'frequency': ts_frequency,
#     'units': ts_units
# }

# response = requests.get(base_url + obs_endpoint, params=cont_claims_params)
# data = response.json()
# cont_claims_df = pd.DataFrame(data['observations'])

# cont_claims_df['date'] = pd.to_datetime(cont_claims_df['date'])
# cont_claims_df['value'] = pd.to_numeric(cont_claims_df['value'], errors='coerce')

# cont_claims_df = (
#     cont_claims_df
#     .set_index('date')[['value']]
#     .resample('ME')
#     .mean()
#     .rename(columns={'value': 'cont_claims'})
# )

In [ ]:
# MARKET YIELD ON 2-YEAR TREASURY SECURITIES -- DAILY

# series_id = 'DGS2'
# start_date = '2000-01-01'
# end_date = '2026-05-01'
# ts_frequency = 'd'
# ts_units = 'lin'

# two_year_yield_params = {
#     'series_id': series_id,
#     'api_key': fred_key,
#     'file_type': 'json',
#     'observation_start': start_date,
#     'observation_end': end_date,
#     'frequency': ts_frequency,
#     'units': ts_units
# }

# response = requests.get(base_url + obs_endpoint, params=two_year_yield_params)
# data = response.json()
# two_year_yield_df = pd.DataFrame(data['observations'])
# two_year_yield_df['date'] = pd.to_datetime(two_year_yield_df['date'])
# two_year_yield_df['value'] = pd.to_numeric(two_year_yield_df['value'], errors='coerce')

# two_year_yield_df = (
#     two_year_yield_df
#     .set_index('date')[['value']]
#     .resample('ME')
#     .last()     # USE LAST OBSERVATION WITH YIELDS, AVERAGES DILUTE THE SIGNAL
#     .rename(columns={'value': 'two_year_yield'})
# )

In [ ]:
# MARKET YIELD ON 10-YEAR TREASURY SECURITIES -- DAILY

# series_id = 'DGS10'
# start_date = '2000-01-01'
# end_date = '2026-05-01'
# ts_frequency = 'd'
# ts_units = 'lin'

# ten_year_yield_params = {
#     'series_id': series_id,
#     'api_key': fred_key,
#     'file_type': 'json',
#     'observation_start': start_date,
#     'observation_end': end_date,
#     'frequency': ts_frequency,
#     'units': ts_units
# }

# response = requests.get(base_url + obs_endpoint, params=ten_year_yield_params)
# data = response.json()  
# ten_year_yield_df = pd.DataFrame(data['observations'])

# ten_year_yield_df['date'] = pd.to_datetime(ten_year_yield_df['date'])
# ten_year_yield_df['value'] = pd.to_numeric(ten_year_yield_df['value'], errors='coerce')

# ten_year_yield_df = (
#     ten_year_yield_df
#     .set_index('date')[['value']]
#     .resample('ME')
#     .last()
#     .rename(columns={'value': 'ten_year_yield'})
# )

In [ ]:
# 10 YEAR TREASURY YIELD SPREAD -- DAILY

# series_id = 'T10Y2Y'
# start_date = '2000-01-01'
# end_date = '2026-05-01'
# ts_frequency = 'd'
# ts_units = 'lin'

# ten_year_treasury_params = {
#     'series_id': series_id,
#     'api_key': fred_key,
#     'file_type': 'json',
#     'observation_start': start_date,
#     'observation_end': end_date,
#     'frequency': ts_frequency,
#     'units': ts_units
# }

# response = requests.get(base_url + obs_endpoint, params=ten_year_treasury_params)
# data = response.json()  
# ten_year_treasury_df = pd.DataFrame(data['observations'])

# ten_year_treasury_df['date'] = pd.to_datetime(ten_year_treasury_df['date'])
# ten_year_treasury_df['value'] = pd.to_numeric(ten_year_treasury_df['value'], errors='coerce')

# ten_year_treasury_df = (
#     ten_year_treasury_df
#     .set_index('date')[['value']]
#     .resample('ME')
#     .last()
#     .rename(columns={'value': 'ten_year_treasury_spread'})
# )

In [ ]:
# UNIVERSITY OF MICHIGAN: CONSUMER SENTIMENT -- MONTHLY

# series_id = 'UMCSENT'
# start_date = '2000-01-01'
# end_date = '2026-05-01'
# ts_frequency = 'm'
# ts_units = 'lin'

# sentiment_params = {
#     'series_id': series_id,
#     'api_key': fred_key,
#     'file_type': 'json',
#     'observation_start': start_date,
#     'observation_end': end_date,
#     'frequency': ts_frequency,
#     'units': ts_units
# }

# response = requests.get(base_url + obs_endpoint, params=sentiment_params)
# data = response.json()
# sentiment_df = pd.DataFrame(data['observations'])
# sentiment_df['date'] = pd.to_datetime(sentiment_df['date'])
# sentiment_df['value'] = pd.to_numeric(sentiment_df['value'], errors='coerce')
# sentiment_df = (
#     sentiment_df
#     .set_index('date')[['value']]
#     .resample('ME')
#     .last()
#     .rename(columns={'value': 'sentiment'})
# )

In [ ]:
# fred_data_df = (
#     payems_df
#     .join(unemp_claims_df, how='outer')
#     .join(cont_claims_df, how='outer')  
#     .join(two_year_yield_df, how='outer')
#     .join(ten_year_yield_df, how='outer')
#     .join(ten_year_treasury_df, how='outer')
#     .join(sentiment_df, how='outer')

# )

In [ ]:
# fred_data_df['sentiment_lag1'] = fred_data_df['sentiment'].shift(1) # LAGGED SENTIMENT TO AVOID LOOKAHEAD BIAS IN MODELING
# fred_data_df['']

#### BLS DATA WRANGLING & CLEANING

In [170]:
import json
import prettytable
bls_key = os.getenv('BLS')

In [171]:
BLS_ENDPOINT = "https://api.bls.gov/publicAPI/v2/timeseries/data/"

def fetch_bls_series(series, **kwargs):
    # """
    # Pass in a list of BLS timeseries to fetch data and return the series
    # in JSON format. Arguments can also be provided as kwargs:
    #     - startyear (4 digit year)
    #     - endyear (4 digit year)
    #     - catalog (True or False)
    #     - calculations (True or False)
    #     - annualaverage (True or False)
    #     - registrationKey (api key from BLS website)
    # If the registrationKey is not passed in, this function will use the
    # BLS_API_KEY fetched from the environment.
    # """
    if len(series) < 1 or len(series) > 25:
        raise ValueError("Must pass in between 1 and 25 series ids")
    # Create headers and payload post data
    headers = {'Content-Type': 'application/json'}
    payload = {
        'seriesid': series,
        'registrationKey': bls_key,
    }
    # Update the payload with the keyword arguments and convert to JSON
    payload.update(kwargs)
    payload = json.dumps(payload)
    # Fetch the response from the BLS API
    response = requests.post(BLS_ENDPOINT, data=payload, headers=headers)
    response.raise_for_status()
    # Parse the JSON result
    #result = response.json()
    result = json.loads(response.text)
    if result['status'] != 'REQUEST_SUCCEEDED':
        raise Exception(result['message'][0])
    return result

In [172]:
series = ['JTS000000000000000JOR', 'JTS000000000000000HIR', 'JTS000000000000000QUR', 'JTS000000000000000LDR']
start_year = 1999
end_year = 2026
json_data = fetch_bls_series(series, startyear=start_year, endyear=end_year)

In [173]:
try:
    # Create a list to store individual DataFrames
    dfs = []

    for series in json_data['Results']['series']:
        df_initial = pd.DataFrame(series)
        series_col = df_initial['seriesID'][0]

        for i in range(0, len(df_initial) - 1):
            df_row = pd.DataFrame(df_initial['data'][i])
            df_row['seriesID'] = series_col

            if 'code' not in str(df_row['footnotes']): 
                df_row['footnotes'] = ''
            else:
                df_row['footnotes'] = str(df_row['footnotes']).split("'code': '", 1)[1][:1]

            # Append df_row to the list
            dfs.append(df_row)

    # Concatenate the list of DataFrames into a single DataFrame
    df = pd.concat(dfs, ignore_index=True)

    # Save the final DataFrame to a CSV file
    df.to_csv('blsdata.csv', index=False)

except Exception as e:
    json_data['status'] == 'REQUEST_NOT_PROCESSED'
    print('BLS API has given the following Response:', json_data['status'])
    print('Reason:', json_data['message'])
    print('Error:', str(e))

In [174]:
openings_df = (
    df[df['seriesID'] == 'JTS000000000000000JOR']
    #.drop_duplicates('periodName')
    .set_index('periodName')[['value', 'year']]
    .rename(columns={'value':'job openings rate'})
)

hires_df = (
    df[df['seriesID'] == 'JTS000000000000000HIR']
    #.drop_duplicates('periodName')
    .set_index('periodName')[['value']]
    .rename(columns={'value':'hires rate'})
)

quit_df = (
    df[df['seriesID'] == 'JTS000000000000000QUR']
    #.drop_duplicates('periodName')
    .set_index('periodName')[['value']]
    .rename(columns={'value':'quit rate'})
)

discharge_df = (
    df[df['seriesID'] == 'JTS000000000000000LDR']
    #.drop_duplicates('periodName')
    .set_index('periodName')[['value']]
    .rename(columns={'value':'discharge rate'})
)

bls_01_09_df = (
    openings_df
    .join(hires_df, how='outer')
    .join(quit_df, how='outer')
    .join(discharge_df, how='outer')
)

print(bls_01_09_df['year'].unique())
bls_01_09_df

['2018' '2017' '2016' '2015' '2014' '2013' '2012' '2011' '2010' '2009'
 '2008' '2007' '2006' '2005' '2004' '2003' '2002' '2001']

           job openings rate  year hires rate quit rate discharge rate
periodName
April                    4.4  2018        3.8       2.3            1.2
April                    4.4  2018        3.8       2.3            1.2
April                    4.4  2018        3.8       2.3            1.2
April                    4.4  2018        3.8       2.3            1.3
April                    4.4  2018        3.8       2.3            1.3
...                      ...   ...        ...       ...            ...
September                3.0  2001        3.8       2.1            1.5
September                3.0  2001        3.8       2.1            1.5
September                3.0  2001        3.8       2.1            1.5
September                3.0  2001        3.8       2.1            1.5
September                3.0  2001        3.8       2.1            1.6

[1259712 rows x 5 columns]

In [175]:
series = ['JTS000000000000000JOR', 'JTS000000000000000HIR', 'JTS000000000000000QUR', 'JTS000000000000000LDR']
start_year = 2019
end_year = 2026
json_data = fetch_bls_series(series, startyear=start_year, endyear=end_year)

In [176]:
try:
    # Create a list to store individual DataFrames
    dfs = []

    for series in json_data['Results']['series']:
        df_initial = pd.DataFrame(series)
        series_col = df_initial['seriesID'][0]

        for i in range(0, len(df_initial) - 1):
            df_row = pd.DataFrame(df_initial['data'][i])
            df_row['seriesID'] = series_col

            if 'code' not in str(df_row['footnotes']): 
                df_row['footnotes'] = ''
            else:
                df_row['footnotes'] = str(df_row['footnotes']).split("'code': '", 1)[1][:1]

            # Append df_row to the list
            dfs.append(df_row)

    # Concatenate the list of DataFrames into a single DataFrame
    df = pd.concat(dfs, ignore_index=True)

    # Save the final DataFrame to a CSV file
    df.to_csv('blsdata.csv', index=False)

except Exception as e:
    json_data['status'] == 'REQUEST_NOT_PROCESSED'
    print('BLS API has given the following Response:', json_data['status'])
    print('Reason:', json_data['message'])
    print('Error:', str(e))

In [177]:
openings_df = (
    df[df['seriesID'] == 'JTS000000000000000JOR']
    #.drop_duplicates('periodName')
    .set_index('periodName')[['value', 'year']]
    .rename(columns={'value':'job openings rate'})
)

hires_df = (
    df[df['seriesID'] == 'JTS000000000000000HIR']
    #.drop_duplicates('periodName')
    .set_index('periodName')[['value']]
    .rename(columns={'value':'hires rate'})
)

quit_df = (
    df[df['seriesID'] == 'JTS000000000000000QUR']
    #.drop_duplicates('periodName')
    .set_index('periodName')[['value']]
    .rename(columns={'value':'quit rate'})
)

discharge_df = (
    df[df['seriesID'] == 'JTS000000000000000LDR']
    #.drop_duplicates('periodName')
    .set_index('periodName')[['value']]
    .rename(columns={'value':'discharge rate'})
)

bls_10_09_df = (
    openings_df
    .join(hires_df, how='outer')
    .join(quit_df, how='outer')
    .join(discharge_df, how='outer')
)
print(bls_10_09_df['year'].unique())
bls_10_09_df

['2025' '2024' '2023' '2022' '2021' '2020' '2019' '2026']

           job openings rate  year hires rate quit rate discharge rate
periodName
April                    4.3  2025        3.4       2.0            1.1
April                    4.3  2025        3.4       2.0            1.0
April                    4.3  2025        3.4       2.0            1.1
April                    4.3  2025        3.4       2.0            0.9
April                    4.3  2025        3.4       2.0            1.0
...                      ...   ...        ...       ...            ...
September                4.5  2019        3.9       2.3            1.0
September                4.5  2019        3.9       2.3            0.9
September                4.5  2019        3.9       2.3            1.0
September                4.5  2019        3.9       2.3            1.1
September                4.5  2019        3.9       2.3            1.3

[32202 rows x 5 columns]

In [178]:
bls_df = pd.concat([bls_01_09_df, bls_10_09_df]).reset_index()

In [179]:
bls_df['month_year'] = bls_df['periodName'] + ' ' + bls_df['year'].astype(str)

In [180]:
num_cols = [
    'job openings rate',
    'hires rate',
    'quit rate',
    'discharge rate'
    ]
bls_df[num_cols] = bls_df[num_cols].apply(
    pd.to_numeric,
    errors='coerce'
)

In [181]:
bls_df = bls_df.groupby(
    'month_year'
    ).agg(
        job_opening_rate = ('job openings rate', 'mean'),
        hire_rate = ('hires rate', 'mean'),
        quit_rate = ('quit rate', 'mean'),
        discharge_rate = ('discharge rate', 'mean')
    ).reset_index()
print(bls_df.dtypes)
bls_df.head()

month_year           object
job_opening_rate    float64
hire_rate           float64
quit_rate           float64
discharge_rate      float64
dtype: object

   month_year  job_opening_rate  hire_rate  quit_rate  discharge_rate
0  April 2001               3.4        3.6   1.894444        1.405556
1  April 2002               2.6        3.6   1.894444        1.405556
2  April 2003               2.3        3.6   1.894444        1.405556
3  April 2004               2.6        3.6   1.894444        1.405556
4  April 2005               3.0        3.6   1.894444        1.405556

In [182]:
bls_df['month_year'] = pd.to_datetime(bls_df['month_year'])

bls_df['month'] = bls_df['month_year'].dt.month
bls_df['year'] = bls_df['month_year'].dt.year

C:\Users\paulp\AppData\Local\Temp\ipykernel_42340\2268307120.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  bls_df['month_year'] = pd.to_datetime(bls_df['month_year'])

In [191]:
bls_df['jor_3mo_avg'] = bls_df['job_opening_rate'].rolling(3).mean()
bls_df['jor_momentum'] = bls_df['job_opening_rate'].diff(3)
bls_df['hire_3mo_avg'] = bls_df['hire_rate'].rolling(3).mean()
bls_df['hire_momentum'] = bls_df['hire_rate'].diff(3)
bls_df['quit_3mo_avg'] = bls_df['quit_rate'].rolling(3).mean()
bls_df['quit_momentum'] = bls_df['quit_rate'].diff(3)
bls_df['discharge_3mo_avg'] = bls_df['discharge_rate'].rolling(3).mean()
bls_df['discharge_momentum'] = bls_df['discharge_rate'].diff(3)

#### FRED/BLS COMBINED DF

In [192]:
fred_df['month'] = fred_df['DATE'].dt.month
fred_df['year'] = fred_df['DATE'].dt.year

In [193]:
bls_df['month']
bls_df = bls_df.sort_values('month_year').reset_index()

In [194]:
master_df = pd.merge(
    fred_df,
    bls_df,
    on=['year', 'month'],
    how='inner'
)

In [198]:
master_df = master_df.dropna()

#### OLS PROXY FOR PREDICTED PAYROLL

In [199]:
master_df.head()

,DATE,payrolls,unemployment_rate,initial_claims,cont_claims,2yr_yield,10yr_yield,10yr_2yr_spread,sentiment,payrolls_lag1,...,quit_rate,discharge_rate,jor_3mo_avg,jor_momentum,hire_3mo_avg,hire_momentum,quit_3mo_avg,quit_momentum,discharge_3mo_avg,discharge_momentum
3,2001-04-30,132458.0,4.4,396750.0,2697250.0,4.234000,5.141000,0.907000,88.4,132751.0,...,1.894444,1.405556,3.533333,-0.4,3.611111,-0.005556,1.898148,0.000000,1.405556,-0.016667
4,2001-05-31,132408.0,4.3,394500.0,2819250.0,4.260000,5.391364,1.131364,92.0,132458.0,...,1.877778,1.400000,3.366667,-0.5,3.616667,0.016667,1.888889,-0.027778,1.409259,0.011111
5,2001-06-30,132300.0,4.5,397200.0,2947400.0,4.080000,5.284286,1.204286,92.6,132408.0,...,1.888889,1.416667,3.266667,-0.3,3.603704,-0.038889,1.887037,-0.005556,1.407407,-0.005556
6,2001-07-31,132172.0,4.6,398000.0,3030750.0,4.038571,5.236190,1.197619,92.4,132300.0,...,1.872222,1.411111,3.233333,-0.1,3.603704,0.000000,1.879630,-0.022222,1.409259,0.005556
7,2001-08-31,132021.0,4.9,398000.0,3120000.0,3.757391,4.971304,1.213913,91.5,132172.0,...,1.883333,1.405556,3.166667,-0.2,3.600000,-0.011111,1.881481,0.005556,1.411111,0.005556

In [203]:
print(master_df.columns)

Index(['DATE', 'payrolls', 'unemployment_rate', 'initial_claims',
       'cont_claims', '2yr_yield', '10yr_yield', '10yr_2yr_spread',
       'sentiment', 'payrolls_lag1', 'unemployment_rate_3mo_avg',
       'initial_claims_lag1', 'initial_claims_momentum', 'cont_claims_lag1',
       'cont_claims_momentum', '2yr_yield_volatility', '10yr_yield_volatility',
       'month', 'year', 'level_0', 'index', 'month_year', 'job_opening_rate',
       'hire_rate', 'quit_rate', 'discharge_rate', 'jor_3mo_avg',
       'jor_momentum', 'hire_3mo_avg', 'hire_momentum', 'quit_3mo_avg',
       'quit_momentum', 'discharge_3mo_avg', 'discharge_momentum'],
      dtype='object')

In [208]:
X = master_df[['unemployment_rate', 'initial_claims', 'cont_claims', '2yr_yield', '10yr_yield', '10yr_2yr_spread']]
X = sm.add_constant(X)

y = master_df['payrolls']

model = sm.OLS(y, X).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               payrolls   R-squared:                       0.751
Model:                            OLS   Adj. R-squared:                  0.747
Method:                 Least Squares   F-statistic:                     168.4
Date:                Sun, 24 May 2026   Prob (F-statistic):           4.63e-82
Time:                        12:57:31   Log-Likelihood:                -2787.9
No. Observations:                 285   AIC:                             5588.
Df Residuals:                     279   BIC:                             5610.
Df Model:                           5
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const              1.637e+05   1322.458    123.804      0.000    1.61e+05    1.66e+05
unemployment_rate -1290.2543    280.022     -4.608      0.000   -1841.478    -739.031
initial_claims       -0.0013      0.001     -1.037      0.301      -0.004       0.001
cont_claims          -0.0004      0.000     -1.787      0.075      -0.001    4.11e-05
2yr_yield           706.2467    162.025      4.359      0.000     387.299    1025.194
10yr_yield        -3481.3658    196.356    -17.730      0.000   -3867.893   -3094.839
10yr_2yr_spread   -4187.6125    279.564    -14.979      0.000   -4737.935   -3637.290
==============================================================================
Omnibus:                       19.755   Durbin-Watson:                   0.069
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               24.096
Skew:                           0.554   Prob(JB):                     5.86e-06
Kurtosis:                       3.895   Cond. No.                     6.92e+21
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.02e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [209]:
master_df['predicted_payrolls'] = model.predict(X)

C:\Users\paulp\AppData\Local\Temp\ipykernel_42340\4005956054.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df['predicted_payrolls'] = model.predict(X)

In [210]:
master_df.head()

,DATE,payrolls,unemployment_rate,initial_claims,cont_claims,2yr_yield,10yr_yield,10yr_2yr_spread,sentiment,payrolls_lag1,...,discharge_rate,jor_3mo_avg,jor_momentum,hire_3mo_avg,hire_momentum,quit_3mo_avg,quit_momentum,discharge_3mo_avg,discharge_momentum,predicted_payrolls
3,2001-04-30,132458.0,4.4,396750.0,2697250.0,4.234000,5.141000,0.907000,88.4,132751.0,...,1.405556,3.533333,-0.4,3.611111,-0.005556,1.898148,0.000000,1.405556,-0.016667,137742.953616
4,2001-05-31,132408.0,4.3,394500.0,2819250.0,4.260000,5.391364,1.131364,92.0,132458.0,...,1.400000,3.366667,-0.5,3.616667,0.016667,1.888889,-0.027778,1.409259,0.011111,136032.580629
5,2001-06-30,132300.0,4.5,397200.0,2947400.0,4.080000,5.284286,1.204286,92.6,132408.0,...,1.416667,3.266667,-0.3,3.603704,-0.038889,1.887037,-0.005556,1.407407,-0.005556,135659.395850
6,2001-07-31,132172.0,4.6,398000.0,3030750.0,4.038571,5.236190,1.197619,92.4,132300.0,...,1.411111,3.233333,-0.1,3.603704,0.000000,1.879630,-0.022222,1.409259,0.005556,135661.642394
7,2001-08-31,132021.0,4.9,398000.0,3120000.0,3.757391,4.971304,1.213913,91.5,132172.0,...,1.405556,3.166667,-0.2,3.600000,-0.011111,1.881481,0.005556,1.411111,0.005556,135893.720702

In [212]:
predicted = master_df.pop('predicted_payrolls')
master_df.insert(2, 'predicted_payrolls', predicted)

In [216]:
master_df['payrolls_difference'] = (master_df['payrolls'] - master_df['predicted_payrolls'])
diff = master_df.pop('payrolls_difference')
master_df.insert(3,'payrolls_difference', diff)

C:\Users\paulp\AppData\Local\Temp\ipykernel_42340\1165071664.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df['payrolls_difference'] = (master_df['payrolls'] - master_df['predicted_payrolls'])

In [217]:
master_df.head()

,DATE,payrolls,predicted_payrolls,payrolls_difference,unemployment_rate,initial_claims,cont_claims,2yr_yield,10yr_yield,10yr_2yr_spread,...,quit_rate,discharge_rate,jor_3mo_avg,jor_momentum,hire_3mo_avg,hire_momentum,quit_3mo_avg,quit_momentum,discharge_3mo_avg,discharge_momentum
3,2001-04-30,132458.0,137742.953616,-5284.953616,4.4,396750.0,2697250.0,4.234000,5.141000,0.907000,...,1.894444,1.405556,3.533333,-0.4,3.611111,-0.005556,1.898148,0.000000,1.405556,-0.016667
4,2001-05-31,132408.0,136032.580629,-3624.580629,4.3,394500.0,2819250.0,4.260000,5.391364,1.131364,...,1.877778,1.400000,3.366667,-0.5,3.616667,0.016667,1.888889,-0.027778,1.409259,0.011111
5,2001-06-30,132300.0,135659.395850,-3359.395850,4.5,397200.0,2947400.0,4.080000,5.284286,1.204286,...,1.888889,1.416667,3.266667,-0.3,3.603704,-0.038889,1.887037,-0.005556,1.407407,-0.005556
6,2001-07-31,132172.0,135661.642394,-3489.642394,4.6,398000.0,3030750.0,4.038571,5.236190,1.197619,...,1.872222,1.411111,3.233333,-0.1,3.603704,0.000000,1.879630,-0.022222,1.409259,0.005556
7,2001-08-31,132021.0,135893.720702,-3872.720702,4.9,398000.0,3120000.0,3.757391,4.971304,1.213913,...,1.883333,1.405556,3.166667,-0.2,3.600000,-0.011111,1.881481,0.005556,1.411111,0.005556

In [221]:
print('diff under 0: ', (master_df['payrolls_difference'] < 0).sum())
print('diff over 0: ', (master_df['payrolls_difference'] > 0).sum())

diff under 0:  140
diff over 0:  145

In [225]:
threshold = 100

master_df['surprise'] = np.where(
    master_df['payrolls_difference'] > threshold,
    1,
    np.where(
        master_df['payrolls_difference'] < -threshold,
        -1,
        0
    )
)

C:\Users\paulp\AppData\Local\Temp\ipykernel_42340\3509330022.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df['surprise'] = np.where(

In [226]:
print('1: ', (master_df['surprise'] == 1).sum())
print('-1: ', (master_df['surprise'] == -1).sum())
print('0: ', (master_df['surprise'] == 0).sum())

1:  139
-1:  138
0:  8